
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.36.32532.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.36.32532.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6y8gfo"
      binary: "C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6y8gfo"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6y8gfo
        
        Run Build Command(s):C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_851ba\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_851ba.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_851ba.dir\\build
        Building C object CMakeFiles/cmTC_851ba.dir/CMakeCCompilerABI.c.obj
        	C:\\Users\\santi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_851ba.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-6y8gfo --filter-prefix="Note: including file: " -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe" @C:\\Users\\santi\\AppData\\Local\\Temp\\nm37F.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_851ba.exe
        	C:\\Users\\santi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_851ba.dir --rc="C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe" --mt="C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe" --manifests -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe" /nologo @CMakeFiles\\cmTC_851ba.dir\\objects1.rsp @C:\\Users\\santi\\AppData\\Local\\Temp\\nm3FD.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_851ba.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_851ba.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_851ba.dir/manifest.res CMakeFiles\\cmTC_851ba.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_851ba.dir\\objects1.rsp /out:cmTC_851ba.exe /implib:cmTC_851ba.lib /pdb:C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-6y8gfo\\cmTC_851ba.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_851ba.dir/intermediate.manifest CMakeFiles\\cmTC_851ba.dir/manifest.res
        MT:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_851ba.dir/intermediate.manifest /out:CMakeFiles\\cmTC_851ba.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_851ba.dir/manifest.res CMakeFiles\\cmTC_851ba.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_851ba.dir\\objects1.rsp /out:cmTC_851ba.exe /implib:cmTC_851ba.lib /pdb:C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-6y8gfo\\cmTC_851ba.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_851ba.dir/intermediate.manifest CMakeFiles\\cmTC_851ba.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xftb9o"
      binary: "C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xftb9o"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/santi/Documents/Progra3/Examen1/Examen1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xftb9o
        
        Run Build Command(s):C:/Users/santi/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_72629\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_72629.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_72629.dir\\build
        Building CXX object CMakeFiles/cmTC_72629.dir/CMakeCXXCompilerABI.cpp.obj
        	C:\\Users\\santi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_72629.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-xftb9o --filter-prefix="Note: including file: " -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe" @C:\\Users\\santi\\AppData\\Local\\Temp\\nm718.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_72629.exe
        	C:\\Users\\santi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_72629.dir --rc="C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe" --mt="C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe" --manifests -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe" /nologo @CMakeFiles\\cmTC_72629.dir\\objects1.rsp @C:\\Users\\santi\\AppData\\Local\\Temp\\nm7C5.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_72629.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_72629.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_72629.dir/manifest.res CMakeFiles\\cmTC_72629.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_72629.dir\\objects1.rsp /out:cmTC_72629.exe /implib:cmTC_72629.lib /pdb:C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-xftb9o\\cmTC_72629.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_72629.dir/intermediate.manifest CMakeFiles\\cmTC_72629.dir/manifest.res
        MT:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_72629.dir/intermediate.manifest /out:CMakeFiles\\cmTC_72629.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_72629.dir/manifest.res CMakeFiles\\cmTC_72629.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_72629.dir\\objects1.rsp /out:cmTC_72629.exe /implib:cmTC_72629.lib /pdb:C:\\Users\\santi\\Documents\\Progra3\\Examen1\\Examen1\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-xftb9o\\cmTC_72629.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_72629.dir/intermediate.manifest CMakeFiles\\cmTC_72629.dir/manifest.res
        
      exitCode: 0
...
